server:
  address: 192.168.188.65
  port: 8080
  tomcat:
    threads:
      max: 1000 # 最大线程数
      min-spare: 100 # 最小空闲线程数
    max-connections: 1000 # 最大连接数
    accept-count: 100 # 等待队列长度
#logging:
#  level:
#    "[com.multiplethread.judge]": DEBUG